### ISSUE TITLE
Contact form in helpdesk section not working

### ISSUE THREAD

**Issue by ijansch** [Green-Software-Foundation/greensoftware.foundation#11]
I initially tried to report https://github.com/Green-Software-Foundation/greensoftware.foundation/issues/10 via the contactform on the site (Helpdesk menu item in the footer).

When submitting the form, you get an error "Form closed. Please contact your administrator for further assistance."

**Comment by nathany** [comment]
The same error message occurs.

![form-closed](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/4566/907f9093-9fea-4736-9810-a037dbec5d0b)

It appears to be using `forms.zohopublic.eu`

**Comment by russelltrow** [comment]
Hi @nathany thanks letting us know, I will raise this internally and come back to you with an update.

In the meantime please send your request to help[at]greensoftware.foundation and we will get right on it.

**Comment by seanmcilroy29** [comment]
@nathany - could you paste the webpage link you're experiencing issues with?

**Comment by seanmcilroy29** [comment]
The footer 'Helpdesk' link has been updated to point to a helpdesk Google form.
