### ISSUE TITLE
Make register form work even if GitHub is blocked

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/greensoftware.foundation#12]
For HSBC, GitHub is blocked (we're working to unblock just the GSF org on GitHub for HSBC).

However when they submit the register form nothing happens, no error or anything - we debugged live and this error is on the page (there were lots of other errors pre-submission but this one looked like the main one)

![Screenshot 2023-08-04 111307](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/897523/0440c223-3493-4639-987b-48dabf98b7d4)

I suspect the form is doing the check to make sure the GitHub user id is real and this is blocking the form.

## Solution

- Let the user know the form isn't submitting and there is an an error (at least)
- Let the user know that GitHub is blocked and to submit the form on a computer where GitHub is not blocked.
- If GH is blocked just let the user submit anyway, it's better they are in the system.

**Comment by osamajandali** [comment]
@jawache,

You are correct, I am conducting a verification process to ensure that each registrant possesses a valid GitHub account. When a username doesn't exist on GitHub, I'm currently displaying an error message. However, I've realized that when the API is blocked, the users are left without any indication of what might be happening.

To address this, I'd like to propose the following solution:
1. **Keep the exisiting check:** Let's prevent users from submitting the form if the GitHub username doesn't exist. This will ensure that only valid GitHub users are registered if the API is not blocked.

2. **API Blocking Alert:** In the event that our API is blocked, we can provide more informative guidance to the user. We'll display an alert that reads: "It appears that GitHub is currently inaccessible on your network. We are in the process of validating your GitHub username. If you're confident that your GitHub username is accurate, you can proceed by clicking 'Submit Anyway'." We'll accompany this message with a prominently displayed button labeled 'Submit Anyway'.


Please let me know if you believe this solution is appropriate or if you have any further suggestions.

**Comment by jawache** [comment]
Sure that works

**Comment by zanete** [comment]
Capture status on the weekly call:
- will start working on it this week

**Comment by osamajandali** [comment]
Fixed! should be good now

**Comment by zanete** [comment]
Assuming it works until we're told otherwise. cc @jawache
