### ISSUE TITLE
Subcribe form for members of GSF requires at least 1 WG and 1 Project

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/greensoftware.foundation#14]
In order to subscribe to a Working group, at least 1 project needs to be selected (and vice versa for subscribing to to a project).

I wanted to join Community WG meetings, but needed to subscribe to at least 1 project for the form to submit, is this the desired behaviour?

If so, on failed form submission I suggest we add some feedback to the website user that they need to select at least 1 WG and 1 project (or highlight them in red).

**Comment by seanmcilroy29** [comment]
@Asim - Remove * mandatory requirement for members to subscribe to a WG and Project - [Subscription Form](https://greensoftware.foundation/subscribe/)

**Comment by seanmcilroy29** [comment]
Subscribe form updated
