### ISSUE TITLE
Update "How we work" website page

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/greensoftware.foundation#15]
https://greensoftware.foundation/articles/welcome-to-the-green-software-foundation

Currently refers to "Innovation" & "trademark" working groups rather than "Open Source" & "Policy"

**Comment by zanete** [comment]
Updated via DatoCMS: https://green-software-foundation.admin.datocms.com/editor/item_types/1245864/items/66393788/edit?filter%5Bquery%5D=welcome-to-the-green-software-foundation 
cc @russelltrow

**Comment by russelltrow** [comment]
Perfect thank you
