### ISSUE TITLE
Theory of Change article has a Google Drive link that isn't public

### ISSUE THREAD

**Issue by LautaroLobo12** [Green-Software-Foundation/greensoftware.foundation#16]
At the final paragraph of the [Theory of Change article](https://greensoftware.foundation/articles/theory-of-change) there's a sentence that reads:

> Please find the link to our full Theory of Change deck [here.](https://drive.google.com/file/d/1FqNQESbG4WrWr4CUlOODzBVaY9sM9dZ4/)

That link says that I need permission to access. Why then is that link made public through the article? It should be of public access, or it shouldn't be in the article.

**Comment by russelltrow** [comment]
Hi @LautaroLobo12, thank you so much for raising this. The PDF should be publicly accessible so let me see what's gone wrong.

Russ
