### ISSUE TITLE
Newletter signup is erroring

### ISSUE THREAD

**Issue by nathany** [Green-Software-Foundation/greensoftware.foundation#19]
The newsletter signup is resulting in a timeout error in the console.

![newsletter](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/4566/54c51b41-67e2-4456-95b9-68e0de9fb6f2)

Testing in Firefox Developer Edition 121.0b9.

**Comment by NAMRATA-WOKE** [comment]
@jawache did you make any changes on Mailchimp recently?

**Comment by NAMRATA-WOKE** [comment]
@jawache how can I check if this has been resolved? Shall I try and sign up and see if I get added to the newsletter?

**Comment by jawache** [comment]
@nathany and @NAMRATA-WOKE perhaps please try again? Signups in general are working I can see dozens of people signing up a day so there is nothing broken in general. 

@nathany does it work if you run in incognito mode? It could be a plugin interaction with MailChimp?

**Comment by nathany** [comment]
@jawache Same error. Have you tried to reproduce it in Firefox with the developer console open?

Same error with private browsing:

![private-browsing](https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/4566/e405fe80-cf3b-4818-9821-cc04c07d3940)

**Comment by jawache** [comment]
Thanks @osamajandali could you take a look at this please?

**Comment by osamajandali** [comment]
The issue arises due to the tracking protection feature in Firefox's private browsing mode. Specifically, this mode blocks certain tracking elements, which appears to be affecting the embedded Mailchimp form, possibly due to its tracking components which I have no control of. It's important to note that Firefox's private mode also disables Google Analytics tracking. However, this problem does not occur in a standard, non-private Firefox window.

**Comment by jawache** [comment]
Thanks @osamajandali , so assuming there is nothing we can do here right?

**Comment by nathany** [comment]
FYI, I use uBlock Origin, so that may also be related to the issue.

**Comment by osamajandali** [comment]
@jawache Yes, we don't have any control over mailchimp forms

**Comment by jawache** [comment]
Gotcha thanks, so unfortunately @nathany looks like this is something related to your Firefox settings and we can't resolve 😕

**Comment by nathany** [comment]
Okay
