### ISSUE TITLE
How do we update one our logo since our rebrand?

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/greensoftware.foundation#20]
Hi there,

Is there a way to update the image we use for our organisation's logo? Here's how it looks right now:

<img width="718" alt="Screenshot 2024-03-13 at 17 48 42" src="https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/17906/f20a3583-7f5c-4985-b9cc-f65a44a69900">

We rebranded last year, and the assets to use should be accessible at the link below:

https://github.com/thegreenwebfoundation/GWF-brand-assets/tree/master/Logos/pngs

I'd make a PR, but I don't know how to use Gatsby - hope that's ok!

**Comment by russelltrow** [comment]
Hey @mrchrisadams thanks for flagging this, I'll ask our Web Dev @osamajandali to update the logo

**Comment by seanmcilroy29** [comment]
@mrchrisadams - Forward me the new logo and I'll update it

**Comment by seanmcilroy29** [comment]
@mrchrisadams - The logo has been updated - https://greensoftware.foundation/

**Comment by mrchrisadams** [comment]
Wow, that was fast! Thanks fellas!
