### ISSUE TITLE
Fix homepage links

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/greensoftware.foundation#6]
These links are apparently all broken now :/ 

![image](https://user-images.githubusercontent.com/897523/223747245-f4155e5e-5a7c-4945-a941-2f386106b015.png)

Let's not fix it just yet, want the links to goto our WIKI which isn't ready :/

**Comment by osamajandali** [comment]
Shall I remove the links for now, until the wiki is ready ?

**Comment by zanete** [comment]
Capturing the status on weekly web call:
* as there is no answer, keeping this on hold without any action

**Comment by zanete** [comment]
Capturing status on weekly web call
 - @jawache what is the status of the Wiki, any ideas of when we will have the correct links? For now putting this on hold for another couple of weeks

**Comment by jawache** [comment]
Not yet @zanete

**Comment by zanete** [comment]
@jawache @seanmcilroy29 please let us know when you feel this could be actionable

**Comment by zanete** [comment]
@jawache @seanmcilroy29 is this any closer to actionable now?

**Comment by jawache** [comment]
Yeah you can point people towards the wiki, we're going live middle of next week: https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/950283/Working+Groups
=

**Comment by osamajandali** [comment]
@jawache @zanete I updated the homepage links mentioned about as well as the links in the navbar to point to wiki

**Comment by zanete** [comment]
Putting on hold until i can share the short links for all working groups

**Comment by zanete** [comment]
@osamajandali please go ahead and update the hp links to the following:
- Community: https://grnsft.org/wiki-community-wg
- Standards: https://grnsft.org/wiki-standards-wg
- Open Source: https://grnsft.org/wiki-os-wg
- Policy: https://grnsft.org/wiki-policy-wg

**Comment by osamajandali** [comment]
Updated!
