### ISSUE TITLE
Add ability to embed html in articles for YT vid inclusion and other things

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/greensoftware.foundation#9]
**Why**: To attract more readers and visitors to the articles
**What**: enable creation of more interactive / engaging / richer content
**Scope of work**:
- [ ] able to add html in the middle of the content so that can include yt video embed code and it is playable as part of the article when viewed as reader

**Comment by zanete** [comment]
Delayed due to travelling, rolling over to next week

**Comment by osamajandali** [comment]
You can now easily add YT video when writing a new article.
Here is a quick How-To video


https://github.com/Green-Software-Foundation/greensoftware.foundation/assets/13832392/dbf7dc50-cc39-4655-b4d2-64ec57cf0ac3

**Comment by zanete** [comment]
@adamj89 @NAMRATA-WOKE @ursvill  - please see above comment for how to add YouTube Videos in the Articles via the Dato CMS.
cc @jawache
